from pydantic import BaseModel, Field
from typing import Literal, Optional, Dict
from datetime import datetime
from enum import Enum
import uuid


class ActionType(str, Enum):
    """Trading action types."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class Signal(BaseModel):
    """Signal generated by agents."""
    signal_id: str = Field(default_factory=lambda: f"sig_{int(datetime.now().timestamp())}")
    timestamp: datetime = Field(default_factory=datetime.now)
    pair: str
    action: ActionType
    confidence: float = Field(ge=0, le=100)
    reasoning: str
    agent_votes: Dict[str, str]  # {agent_name: action}
    market_data: Dict
    
    class Config:
        use_enum_values = True


class Position(BaseModel):
    """Open position."""
    position_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    pair: str
    side: Literal["LONG", "SHORT"]
    entry_price: float
    size: float  # in USDT
    quantity: float  # in BTC/ETH
    leverage: int = 1
    stop_loss: float
    take_profit: Optional[float] = None
    opened_at: datetime = Field(default_factory=datetime.now)
    signal_id: str


class Trade(BaseModel):
    """Completed trade."""
    trade_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    position_id: str
    pair: str
    side: Literal["LONG", "SHORT"]
    entry_price: float
    exit_price: float
    size: float
    quantity: float
    pnl: float  # Profit/Loss in USDT
    pnl_percent: float
    fees: float
    opened_at: datetime
    closed_at: datetime = Field(default_factory=datetime.now)
    duration_minutes: int
    exit_reason: Literal["TP", "SL", "SIGNAL", "MANUAL"]


class OrderRequest(BaseModel):
    """Order request to execute."""
    pair: str
    side: Literal["BUY", "SELL"]
    order_type: Literal["MARKET", "LIMIT"]
    quantity: float
    price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
